[project]
name = "self-driving-car"
version = "0.1.0"
description = "A tutorial on self-driving car simulation using pygame."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pygame>=2.6.1",
]

[[tool.uv.index]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true
